name: Test

on: 
  pull_request:
  push:
    branches: master

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        rev: [nightly]

    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Prepare
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ../plenary.nvim

      - name: Run tests
        run: |
          nvim --version
          make test
